### ISSUE TITLE
Tests are failing with errors "NoMethodError: undefined method" and "NameError: undefined local variable or method"

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/ruby_lib#335]
Tests are currently failing when running with commands `rake ios` or `rake android`
See full console logs: https://gist.github.com/JaniJegoroff/4eae0e47e4ac0834a7e3

Looks like tests started to fail after https://github.com/appium/ruby_lib/commit/e9d1986a1e46319bfb42fa30de8c4778f6dbc3fb

**Comment by bootstraponline** [comment]
#336
